# Generated by Django 4.2.7 on 2023-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={},
        ),
        migrations.AddField(
            model_name='parrot',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
